const express = require('express');
const { MongoClient, ServerApiVersion } = require('mongodb');
const cors = require('cors');

const app = express();
const port = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

// Replace <db_password> with your actual MongoDB password
const uri = "mongodb+srv://appdevelopergana_db_user:<AoSgfTMrc05pdoKS.ganaramsaib1f.professional>@cluster0.pk1fn6h.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0";

const client = new MongoClient(uri, {
  serverApi: {
      version: ServerApiVersion.v1,
          strict: true,
              deprecationErrors: true,
                }
                });

                async function run() {
                    try {
                            await client.connect();
                                    const database = client.db('mycompany_db');
                                            const servicesCollection = database.collection('services');
                                                    const usersCollection = database.collection('users');

                                                            // Initial setup for services status
                                                                    await servicesCollection.updateOne(
                                                                                { name: 'Video Editing' },
                                                                                            { $set: { status: 'pending' } },
                                                                                                        { upsert: true }
                                                                                                                );
                                                                                                                        await servicesCollection.updateOne(
                                                                                                                                    { name: 'Script Writing' },
                                                                                                                                                { $set: { status: 'pending' } },
                                                                                                                                                            { upsert: true }
                                                                                                                                                                    );
                                                                                                                                                                            await servicesCollection.updateOne(
                                                                                                                                                                                        { name: 'Content Writing' },
                                                                                                                                                                                                    { $set: { status: 'pending' } },
                                                                                                                                                                                                                { upsert: true }
                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                console.log("Database connected and initialized!");

                                                                                                                                                                                                                                        // Endpoint to get services status for the front-end
                                                                                                                                                                                                                                                app.get('/api/services', async (req, res) => {
                                                                                                                                                                                                                                                            const services = await servicesCollection.find({}).toArray();
                                                                                                                                                                                                                                                                        res.json(services);
                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                        // Admin login endpoint
                                                                                                                                                                                                                                                                                                app.post('/api/admin/login', async (req, res) => {
                                                                                                                                                                                                                                                                                                            const { username, password } = req.body;
                                                                                                                                                                                                                                                                                                                        // A simple check. In a real app, use hashed passwords.
                                                                                                                                                                                                                                                                                                                                    if (username === 'your_admin_username' && password === 'your_admin_password') {
                                                                                                                                                                                                                                                                                                                                                    res.status(200).send('Admin logged in successfully');
                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                res.status(401).send('Invalid credentials');
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                            // Admin endpoint to update service status
                                                                                                                                                                                                                                                                                                                                                                                                                    app.post('/api/admin/update-service', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                const { serviceName, newStatus } = req.body;
                                                                                                                                                                                                                                                                                                                                                                                                                                            await servicesCollection.updateOne(
                                                                                                                                                                                                                                                                                                                                                                                                                                                            { name: serviceName },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { $set: { status: newStatus } }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.status(200).send('Service status updated');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.error(e);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            run().catch(console.dir);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            app.listen(port, () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log(`Server is running on http://localhost:${port}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
